---
- name: Windows updates
  hosts: all
  gather_facts: False
  vars:
    report_server: win1
  
  tasks:
  - name: Wait till winRM port is available
    wait_for_connection:
      timeout: 1200
     
  - name: Gather manually the facts
    setup:
    
  - include_role:
      name: demo.patching.patch_windows

  - block:
    - include_role:
        name: demo.patching.report_server
        tasks_from: iis

    - include_role:
        name: demo.patching.report_windows

    - include_role:
        name: demo.patching.report_windows_patching
    delegate_to: "{{ report_server }}"
    run_once: yes
